changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes ⚠️
      labels:
        - api
    - title: New Features 🎉
      labels:
        - new
    - title: Enhancements 🚀
      labels:
        - enhancement
    - title: Maintenance 🛠
      labels:
        - maint
    - title: Documentation 📗
      labels:
        - doc
    - title: Big Fixes 🐛
      labels:
        - bug
    - title: Unsorted ❓
      labels:
        - "*"
