name: Examples

on: pull_request

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ['3.12']
        operating-system: [ubuntu-latest]
        # Next line should be [1, 2, ..., max-parallel)
        test_group: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv for faster builds
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv pip install --system -e .[test,extras]

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Run examples
        # Make sure to pass max-parallel to --splits
        run: |
          pytest \
            -p no:python \
            --nbval-lax \
            --splits ${{ strategy.max-parallel}} \
            --group ${{ matrix.test_group }} \
            --durations-path test/fixtures/.test_durations_examples \
            --suppress-no-test-exit-code  # so if no tests collected, CI won't break
