name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy-docs:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv for faster builds
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install PoreSpy
        run: |
          uv pip install --system -e .[docs,interactive]

      - name: Build the documentation
        run: |
          cd docs
          make html

      - name: Publish the documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          cname: porespy.org
