name: Nightly

on:
  schedule:
    # Run (on default branch only) at 05:00 (hr:mm) UTC -> 12am EST
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv for faster builds
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install PoreSpy (macOS)
        if : (matrix.os == 'macos-latest') || (matrix.os == 'macos-13')
        run: |
            python -m pip install --upgrade pip
            uv pip install --system -e .[test,extras-macos]

      - name: Install PoreSpy (Windows, Linux)
        if : (matrix.os != 'macos-latest') && (matrix.os != 'macos-13')
        run: |
            python -m pip install --upgrade pip
            uv pip install --system -e .[test,extras]            

      - name: Run tests
        run: |
          pytest -v
