name: Test Duration Logger

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv for faster builds
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install PoreSpy
        run: |
            python -m pip install --upgrade pip
            uv pip install --system -e .[test,extras]            

      - name: Run tests
        run: |
          rm test/fixtures/.test_durations*
          pytest \
            --nbval-lax examples/ \
            --store-durations \
            --durations-path test/fixtures/.test_durations_examples
          pytest test/ \
            --store-durations \
            --durations-path test/fixtures/.test_durations_unit

      - name: Commit and push test duration files
        uses: EndBug/add-and-commit@v9
        with:
          add: 'test/fixtures'
          author_name: github-actions
          author_email: actions@github.com
          message: 'test: Update test duration log.'
